### PR TITLE
fix (fix/origin_text_for_bot_utters): add updating origin text

### PR DESCRIPTION
**Pull request by kudep**
PR for #100 issue

### CODE REVIEW

**Comment by yurakuratov** [comment]
`add_bot_utterance_last_chance` and `add_failure_bot_utterance` should be also updated

**Comment by kudep** [comment]
Does `add_bot_utterance_last_chance_overwrite`  need to be updated too?

**Comment by yurakuratov** [comment]
> Does `add_bot_utterance_last_chance_overwrite` need to be updated too?

I'm not sure what is a use-case for this method.
Also, I am not sure if these lines https://github.com/deepmipt/dp-agent/blob/master/deeppavlov_agent/core/state_manager.py#L80-L84 should be inside of if statement.

@p-rdx can you help us?

**Comment by p-rdx** [comment]
Actually both of them. Otherwise if some of the formatters requires original text from the previous bot utterance, they will fail.

**Pull request merged**
